//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Gæst : hus
{
	public string Voksen
	{
		get;
		set;
	}

	public string Barn
	{
		get;
		set;
	}

	public string Ung
	{
		get;
		set;
	}

}

