//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Beborere : hus
{
	public virtual object Navn
	{
		get;
		set;
	}

	public virtual object Alder
	{
		get;
		set;
	}

	public virtual Opgaver Opgaver
	{
		get;
		set;
	}

}

