//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Opgaver
{
	public virtual object Chefkok
	{
		get;
		set;
	}

	public virtual object Opryder
	{
		get;
		set;
	}

	public virtual object Hjælpekok
	{
		get;
		set;
	}

	public virtual Måltid Måltid
	{
		get;
		set;
	}

}

